version: '2'
services:
    web:
      container_name: app_container
      image: grasp/grasp_app:latest
      ports:
          - 8089:8080
      depends_on:
          - db
    db:
        container_name: db_container
        image: postgres:11.1
        volumes:
            - db_container:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=astrongpassword
            - POSTGRES_USER=web_user
            - POSTGRES_DB=grasp_db
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5434:5432


volumes:
    db_container: {}