language: java

services:
- postgresql

before_script:
  - psql --version
  - psql -f ./src/main/resources/database/create_grasp_schema.sql

#./run-test
# After success, send the coverage report to Coveralls

after_success:
  - mvn clean test jacoco:report coveralls:report
