language: java

services:
- postgresql

before_script:
  - psql --version
  - psql -f ./src/main/resources/database/create_grasp_schema.sql

#./run-test
# After success, send the coverage report to Coveralls
# I'm including the specific jacoco plugin to use and install because this was the only way I could get it to work?

after_success:
  # - mvn clean test jacoco:report coveralls:report
  - mvn clean test org.jacoco:jacoco-maven-plugin:0.7.9:prepare-agent install org.jacoco:jacoco-maven-plugin:0.7.9:report coveralls:report
